import { WorkoutCategory } from '../types';

export type StrengthTierKey = 'novice' | 'beginner' | 'intermediate' | 'proficient' | 'elite';

export interface StrengthTierMeta {
  key: StrengthTierKey;
  level: number; // 1 to 5
  score: number; // 20, 40, 60, 80, 100
  zh: string;
  en: string;
  badgeBg: string;
  badgeText: string;
  description: string;
}

export const STRENGTH_TIERS: Record<StrengthTierKey, StrengthTierMeta> = {
  novice: {
    key: 'novice',
    level: 1,
    score: 20,
    zh: '新手',
    en: 'Novice',
    badgeBg: 'bg-slate-200',
    badgeText: 'text-slate-800',
    description: '掌握动作规范，建立基础肌力',
  },
  beginner: {
    key: 'beginner',
    level: 2,
    score: 40,
    zh: '入门',
    en: 'Beginner',
    badgeBg: 'bg-emerald-100',
    badgeText: 'text-emerald-800',
    description: '规律训练，力量初见成效',
  },
  intermediate: {
    key: 'intermediate',
    level: 3,
    score: 60,
    zh: '进阶',
    en: 'Intermediate',
    badgeBg: 'bg-blue-100',
    badgeText: 'text-blue-800',
    description: '掌握大重量，超越大众平均水平',
  },
  proficient: {
    key: 'proficient',
    level: 4,
    score: 80,
    zh: '熟练',
    en: 'Proficient',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-800',
    description: '资深健身达人，力量与形体出众',
  },
  elite: {
    key: 'elite',
    level: 5,
    score: 100,
    zh: '精英',
    en: 'Elite',
    badgeBg: 'bg-amber-300',
    badgeText: 'text-amber-950',
    description: '竞技级高阶力量水准',
  },
};

export type StrengthFamily = 'upper' | 'lower' | 'bodyweight_reps' | 'none';

/**
 * 5-tier Gender Ratio Curves G (Female / Male benchmark ratio across 5 tiers)
 * Calibrated against Strength Level community data (50M+ lifts)
 */
export const G_CURVES: Record<StrengthFamily, [number, number, number, number, number]> = {
  upper: [0.47, 0.56, 0.62, 0.67, 0.71],
  lower: [0.60, 0.65, 0.69, 0.73, 0.76],
  bodyweight_reps: [0.00, 0.00, 0.36, 0.50, 0.58],
  none: [1.0, 1.0, 1.0, 1.0, 1.0],
};

/**
 * Allometric scaling exponent constants
 */
export const EXPONENT_B = {
  male: 0.92,
  female: 0.70,
  bodyweightReps: 0.40,
};

export const BW_CLAMP_MIN = 45;
export const BW_CLAMP_MAX = 130;
export const REF_BW = 70;

export interface ExerciseStandard {
  name: string;
  aliases: string[];
  primaryCategory: WorkoutCategory;
  /**
   * Compound muscle contribution split (sums to 1.0)
   * Example: 传统硬拉 -> { [WorkoutCategory.Legs]: 0.55, [WorkoutCategory.Back]: 0.45 }
   */
  muscleWeights: Partial<Record<WorkoutCategory, number>>;
  unit: 'kg' | 'min' | 'km' | 'reps';
  /**
   * Standard threshold values for [Novice(20), Beginner(40), Intermediate(60), Proficient(80), Elite(100)]
   * Represents 70kg Male Anchor baseline.
   */
  thresholds: [number, number, number, number, number];
  strengthFamily?: StrengthFamily;
  isDumbbellSingle?: boolean; // Single dumbbell weight (e.g. 20kg dumbbell = 20kg per hand)
  type: 'strength' | 'cardio';
}

/**
 * Standard exercise benchmarks calibrated against international strength standards
 * (StrengthLevel / ExRx / NSCA standards for typical adult lifters)
 * Uses 70kg Male as reference anchor.
 */
export const EXERCISE_STANDARDS: ExerciseStandard[] = [
  // ==================== 胸部 (CHEST) ====================
  {
    name: '杠铃平板卧推',
    aliases: ['卧推', '平板卧推', '杠铃卧推', 'bench press', 'flat bench'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 0.85, [WorkoutCategory.Others]: 0.15 },
    unit: 'kg',
    thresholds: [47, 64, 85, 110, 136],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '哑铃平板卧推',
    aliases: ['哑铃卧推', '哑铃推胸', '平板哑铃推胸', '哑铃平推', 'dumbbell bench press', 'dumbbell press', 'db bench'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 0.85, [WorkoutCategory.Others]: 0.15 },
    unit: 'kg',
    thresholds: [14, 22, 32, 44, 56],
    strengthFamily: 'upper',
    isDumbbellSingle: true,
    type: 'strength',
  },
  {
    name: '哑铃上斜卧推',
    aliases: ['上斜哑铃卧推', '上斜卧推', '上斜哑铃推胸', '哑铃上斜推胸', '上斜推胸', 'incline dumbbell press', 'incline db bench'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 0.75, [WorkoutCategory.Shoulders]: 0.25 },
    unit: 'kg',
    thresholds: [12, 18, 26, 36, 48],
    strengthFamily: 'upper',
    isDumbbellSingle: true,
    type: 'strength',
  },

  {
    name: '杠铃上斜卧推',
    aliases: ['上斜杠铃卧推', '杠铃上斜推', 'incline bench', 'incline bench press', 'barbell incline press'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 0.8, [WorkoutCategory.Shoulders]: 0.2 },
    unit: 'kg',
    thresholds: [35, 48, 64, 83, 102],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '史密斯上斜推胸',
    aliases: ['史密斯卧推', '史密斯推胸', 'smith bench press'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 0.75, [WorkoutCategory.Shoulders]: 0.25 },
    unit: 'kg',
    thresholds: [25, 45, 70, 90, 115],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '蝴蝶机夹胸',
    aliases: ['坐姿夹胸', '器械夹胸', 'pec deck', 'chest fly'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 1.0 },
    unit: 'kg',
    thresholds: [24, 32, 43, 55, 68],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '绳索夹胸',
    aliases: ['龙门架夹胸', 'cable fly', 'cable crossover'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 1.0 },
    unit: 'kg',
    thresholds: [19, 26, 35, 44, 54],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '双杠臂屈伸',
    aliases: ['双杠', '臂屈伸', 'dips'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 0.55, [WorkoutCategory.Others]: 0.35, [WorkoutCategory.Shoulders]: 0.1 },
    unit: 'kg',
    thresholds: [5, 20, 40, 63, 75],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '俯卧撑',
    aliases: ['标准俯卧撑', 'push up', 'pushups'],
    primaryCategory: WorkoutCategory.Chest,
    muscleWeights: { [WorkoutCategory.Chest]: 0.65, [WorkoutCategory.Others]: 0.25, [WorkoutCategory.Shoulders]: 0.1 },
    unit: 'reps',
    thresholds: [5, 20, 40, 64, 89],
    strengthFamily: 'bodyweight_reps',
    type: 'strength',
  },

  // ==================== 背部 (BACK) ====================
  {
    name: '高位下拉',
    aliases: ['下拉', '宽握下拉', 'lat pulldown'],
    primaryCategory: WorkoutCategory.Back,
    muscleWeights: { [WorkoutCategory.Back]: 0.85, [WorkoutCategory.Others]: 0.15 },
    unit: 'kg',
    thresholds: [42, 57, 77, 99, 123],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '杠铃划船',
    aliases: ['俯身杠铃划船', '俯身划船', 'barbell row'],
    primaryCategory: WorkoutCategory.Back,
    muscleWeights: { [WorkoutCategory.Back]: 0.8, [WorkoutCategory.Shoulders]: 0.1, [WorkoutCategory.Others]: 0.1 },
    unit: 'kg',
    thresholds: [40, 56, 77, 101, 127],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '坐姿绳索划船',
    aliases: ['坐姿划船', '绳索划船', 'seated cable row'],
    primaryCategory: WorkoutCategory.Back,
    muscleWeights: { [WorkoutCategory.Back]: 0.85, [WorkoutCategory.Others]: 0.15 },
    unit: 'kg',
    thresholds: [40, 57, 78, 102, 128],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '哑铃单臂划船',
    aliases: ['单臂哑铃划船', '哑铃划船', 'dumbbell row'],
    primaryCategory: WorkoutCategory.Back,
    muscleWeights: { [WorkoutCategory.Back]: 0.85, [WorkoutCategory.Others]: 0.15 },
    unit: 'kg',
    thresholds: [16, 25, 38, 53, 69],
    strengthFamily: 'upper',
    isDumbbellSingle: true,
    type: 'strength',
  },
  {
    name: '传统硬拉',
    aliases: ['硬拉', '标准硬拉', 'deadlift', 'barbell deadlift'],
    primaryCategory: WorkoutCategory.Back,
    muscleWeights: { [WorkoutCategory.Legs]: 0.55, [WorkoutCategory.Back]: 0.45 },
    unit: 'kg',
    thresholds: [75, 103, 137, 175, 216],
    strengthFamily: 'lower',
    type: 'strength',
  },
  {
    name: '引体向上',
    aliases: ['正手引体向上', '反手引体向上', '辅助引体向上', '负重引体向上', '宽距引体向上', '窄距引体向上', 'pull up', 'chin up', 'pullup', 'chinup', 'assisted pull up', 'weighted pull up'],
    primaryCategory: WorkoutCategory.Back,
    muscleWeights: { [WorkoutCategory.Back]: 0.85, [WorkoutCategory.Others]: 0.15 },
    unit: 'kg',
    // Thresholds are effective-load 1RM anchors, not repetition counts.
    // Bodyweight has already been included by calculateEffectiveLoad.
    thresholds: [42, 56, 70, 88, 108],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '直臂下压',
    aliases: ['直臂下拉', '绳索直臂下压', 'straight arm pulldown'],
    primaryCategory: WorkoutCategory.Back,
    muscleWeights: { [WorkoutCategory.Back]: 0.9, [WorkoutCategory.Others]: 0.1 },
    unit: 'kg',
    thresholds: [15, 25, 35, 45, 55],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '山羊挺身',
    aliases: ['罗马椅挺身', '下背挺身', 'hyperextension'],
    primaryCategory: WorkoutCategory.Back,
    muscleWeights: { [WorkoutCategory.Back]: 0.6, [WorkoutCategory.Legs]: 0.4 },
    unit: 'kg',
    thresholds: [0, 10, 20, 35, 50],
    strengthFamily: 'lower',
    type: 'strength',
  },

  // ==================== 腿部 (LEGS) ====================
  {
    name: '杠铃深蹲',
    aliases: ['深蹲', '后蹲', '自由深蹲', 'squat', 'barbell squat'],
    primaryCategory: WorkoutCategory.Legs,
    muscleWeights: { [WorkoutCategory.Legs]: 0.9, [WorkoutCategory.Others]: 0.1 },
    unit: 'kg',
    thresholds: [62, 86, 116, 149, 185],
    strengthFamily: 'lower',
    type: 'strength',
  },
  {
    name: '倒蹬机腿举',
    aliases: ['倒蹬', '腿举', '器械腿举', 'leg press'],
    primaryCategory: WorkoutCategory.Legs,
    muscleWeights: { [WorkoutCategory.Legs]: 1.0 },
    unit: 'kg',
    thresholds: [90, 139, 202, 277, 359],
    strengthFamily: 'lower',
    type: 'strength',
  },
  {
    name: '罗马尼亚硬拉',
    aliases: ['RDL', '直腿硬拉', 'romanian deadlift'],
    primaryCategory: WorkoutCategory.Legs,
    muscleWeights: { [WorkoutCategory.Legs]: 0.75, [WorkoutCategory.Back]: 0.25 },
    unit: 'kg',
    thresholds: [54, 79, 110, 145, 184],
    strengthFamily: 'lower',
    type: 'strength',
  },
  {
    name: '坐姿腿屈伸',
    aliases: ['腿屈伸', '股四头肌屈伸', 'leg extension'],
    primaryCategory: WorkoutCategory.Legs,
    muscleWeights: { [WorkoutCategory.Legs]: 1.0 },
    unit: 'kg',
    thresholds: [42, 65, 95, 130, 169],
    strengthFamily: 'lower',
    type: 'strength',
  },
  {
    name: '俯卧腿弯举',
    aliases: ['腿弯举', '腘绳肌弯举', 'leg curl', 'lying leg curl'],
    primaryCategory: WorkoutCategory.Legs,
    muscleWeights: { [WorkoutCategory.Legs]: 1.0 },
    unit: 'kg',
    thresholds: [34, 52, 76, 103, 134],
    strengthFamily: 'lower',
    type: 'strength',
  },
  {
    name: '哑铃箭步蹲',
    aliases: ['箭步蹲', '弓步蹲', 'lunge', 'dumbbell lunges'],
    primaryCategory: WorkoutCategory.Legs,
    muscleWeights: { [WorkoutCategory.Legs]: 1.0 },
    unit: 'kg',
    thresholds: [8, 16, 27, 41, 57],
    strengthFamily: 'lower',
    isDumbbellSingle: true,
    type: 'strength',
  },
  {
    name: '站姿提踵',
    aliases: ['提踵', '小腿提踵', 'calf raise'],
    primaryCategory: WorkoutCategory.Legs,
    muscleWeights: { [WorkoutCategory.Legs]: 1.0 },
    unit: 'kg',
    thresholds: [40, 76, 126, 189, 260],
    strengthFamily: 'lower',
    type: 'strength',
  },
  {
    name: '杠铃臀推',
    aliases: ['臀推', 'hip thrust', 'barbell hip thrust'],
    primaryCategory: WorkoutCategory.Legs,
    muscleWeights: { [WorkoutCategory.Legs]: 1.0 },
    unit: 'kg',
    thresholds: [52, 88, 135, 193, 257],
    strengthFamily: 'lower',
    type: 'strength',
  },

  // ==================== 肩部 (SHOULDERS) ====================
  {
    name: '坐姿哑铃推举',
    aliases: ['哑铃推肩', '哑铃推举', '推肩', 'dumbbell shoulder press'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Shoulders]: 0.8, [WorkoutCategory.Others]: 0.15, [WorkoutCategory.Chest]: 0.05 },
    unit: 'kg',
    thresholds: [7, 12, 20, 29, 39],
    strengthFamily: 'upper',
    isDumbbellSingle: true,
    type: 'strength',
  },
  {
    name: '杠铃过顶推举',
    aliases: ['杠铃推肩', '军式推举', '过顶推举', 'overhead press', 'military press'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Shoulders]: 0.8, [WorkoutCategory.Others]: 0.15, [WorkoutCategory.Chest]: 0.05 },
    unit: 'kg',
    thresholds: [32, 45, 58, 72, 88],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '哑铃侧平举',
    aliases: ['侧平举', '哑铃飞鸟侧平举', 'lateral raise'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Shoulders]: 1.0 },
    unit: 'kg',
    thresholds: [6, 11, 17, 24, 32],
    strengthFamily: 'upper',
    isDumbbellSingle: true,
    type: 'strength',
  },
  {
    name: '绳索侧平举',
    aliases: ['绳索飞鸟', 'cable lateral raise'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Shoulders]: 1.0 },
    unit: 'kg',
    thresholds: [5, 10, 15, 20, 27],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '俯身哑铃飞鸟',
    aliases: ['俯身飞鸟', '后束飞鸟', 'rear delt fly'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Shoulders]: 0.7, [WorkoutCategory.Back]: 0.3 },
    unit: 'kg',
    thresholds: [7, 11, 16, 22, 29],
    strengthFamily: 'upper',
    isDumbbellSingle: true,
    type: 'strength',
  },
  {
    name: '蝴蝶机反向飞鸟',
    aliases: ['反向飞鸟', '蝴蝶机反飞鸟', 'reverse pec deck', 'reverse fly', 'pec deck reverse fly', 'rear delt machine fly'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Shoulders]: 0.8, [WorkoutCategory.Back]: 0.2 },
    unit: 'kg',
    thresholds: [5, 8, 12, 16, 20],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '绳索面拉',
    aliases: ['面拉', 'face pull'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Shoulders]: 0.6, [WorkoutCategory.Back]: 0.4 },
    unit: 'kg',
    thresholds: [18, 25, 35, 50, 60],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '哑铃前平举',
    aliases: ['前平举', 'front raise'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Shoulders]: 0.85, [WorkoutCategory.Chest]: 0.15 },
    unit: 'kg',
    thresholds: [8, 13, 18, 24, 30],
    strengthFamily: 'upper',
    isDumbbellSingle: true,
    type: 'strength',
  },
  {
    name: '杠铃耸肩',
    aliases: ['耸肩', '哑铃耸肩', 'shrug'],
    primaryCategory: WorkoutCategory.Shoulders,
    muscleWeights: { [WorkoutCategory.Back]: 0.6, [WorkoutCategory.Shoulders]: 0.4 },
    unit: 'kg',
    thresholds: [42, 70, 108, 154, 205],
    strengthFamily: 'upper',
    type: 'strength',
  },

  // ==================== 其它/手臂/核心 (OTHERS / ARMS & CORE) ====================
  {
    name: '杠铃弯举 (二头)',
    aliases: ['杠铃弯举', '二头弯举', 'barbell curl'],
    primaryCategory: WorkoutCategory.Others,
    muscleWeights: { [WorkoutCategory.Others]: 1.0 },
    unit: 'kg',
    thresholds: [18, 28, 41, 57, 74],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '哑铃交替弯举 (二头)',
    aliases: ['哑铃弯举', '交替弯举', 'dumbbell curl'],
    primaryCategory: WorkoutCategory.Others,
    muscleWeights: { [WorkoutCategory.Others]: 1.0 },
    unit: 'kg',
    thresholds: [4, 9, 15, 23, 32],
    strengthFamily: 'upper',
    isDumbbellSingle: true,
    type: 'strength',
  },
  {
    name: '绳索下压 (三头)',
    aliases: ['三头下压', '绳索下压', 'triceps pushdown'],
    primaryCategory: WorkoutCategory.Others,
    muscleWeights: { [WorkoutCategory.Others]: 1.0 },
    unit: 'kg',
    thresholds: [8, 19, 30, 41, 53],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '仰卧臂屈伸 (三头)',
    aliases: ['法国推举', 'skull crusher', 'lying triceps extension'],
    primaryCategory: WorkoutCategory.Others,
    muscleWeights: { [WorkoutCategory.Others]: 1.0 },
    unit: 'kg',
    thresholds: [3, 8, 15, 24, 35],
    strengthFamily: 'upper',
    type: 'strength',
  },
  {
    name: '卷腹 (腹肌)',
    aliases: ['卷腹', '仰卧起坐', 'crunches'],
    primaryCategory: WorkoutCategory.Others,
    muscleWeights: { [WorkoutCategory.Others]: 1.0 },
    unit: 'reps',
    thresholds: [20, 40, 60, 80, 100],
    strengthFamily: 'bodyweight_reps',
    type: 'strength',
  },
  {
    name: '平板支撑',
    aliases: ['plank'],
    primaryCategory: WorkoutCategory.Others,
    muscleWeights: { [WorkoutCategory.Others]: 1.0 },
    unit: 'reps', // represents duration in seconds
    thresholds: [60, 90, 120, 180, 240],
    strengthFamily: 'none',
    type: 'strength',
  },
  {
    name: '健腹轮',
    aliases: ['腹肌轮', 'ab roller'],
    primaryCategory: WorkoutCategory.Others,
    muscleWeights: { [WorkoutCategory.Others]: 1.0 },
    unit: 'reps',
    thresholds: [10, 20, 30, 40, 50],
    strengthFamily: 'bodyweight_reps',
    type: 'strength',
  },
  {
    name: '悬垂举腿',
    aliases: ['举腿', 'hanging leg raise'],
    primaryCategory: WorkoutCategory.Others,
    muscleWeights: { [WorkoutCategory.Others]: 1.0 },
    unit: 'reps',
    thresholds: [10, 15, 20, 25, 30],
    strengthFamily: 'bodyweight_reps',
    type: 'strength',
  },

  // ==================== 有氧 (CARDIO) ====================
  {
    name: '羽毛球',
    aliases: ['打羽毛球', 'badminton'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [20, 40, 60, 90, 120],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '篮球',
    aliases: ['打篮球', '投篮', 'basketball'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [20, 40, 60, 90, 120],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '足球',
    aliases: ['踢足球', 'soccer', 'football'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [30, 45, 60, 90, 120],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '游泳',
    aliases: ['自由泳', '蛙泳', 'swimming', 'swim'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [15, 30, 45, 60, 90],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '网球',
    aliases: ['打网球', 'tennis'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [30, 45, 60, 90, 120],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '乒乓球',
    aliases: ['打乒乓球', '桌球', 'table tennis', 'ping pong'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [20, 40, 60, 90, 120],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '跑步机跑步',
    aliases: ['跑步', '户外跑步', '慢跑', 'running', 'treadmill'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [15, 30, 45, 60, 90],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '动感单车',
    aliases: ['单车', '骑行', '户外骑行', 'cycling', 'spin bike'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [20, 35, 50, 65, 90],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '划船机',
    aliases: ['rower', 'rowing machine'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 0.8, [WorkoutCategory.Back]: 0.2 },
    unit: 'min',
    thresholds: [10, 20, 30, 45, 60],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '跳绳',
    aliases: ['jump rope', 'skipping'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [10, 15, 25, 35, 50],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '爬楼机',
    aliases: ['stairmaster', 'stair climber', '爬楼梯'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 0.85, [WorkoutCategory.Legs]: 0.15 },
    unit: 'min',
    thresholds: [10, 15, 25, 35, 50],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: 'HIIT间歇训练',
    aliases: ['hiit', '间歇训练', 'tabata'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [10, 15, 25, 35, 45],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '拳击 / 搏击操',
    aliases: ['拳击', '搏击', 'boxing', 'kickboxing'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [20, 30, 45, 60, 90],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '椭圆机',
    aliases: ['太空漫步机', 'elliptical'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [15, 30, 45, 60, 90],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '健走 / 散步',
    aliases: ['健走', '快走', '散步', 'walking'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [20, 40, 60, 90, 120],
    strengthFamily: 'none',
    type: 'cardio',
  },
  {
    name: '瑜伽 / 普拉提',
    aliases: ['瑜伽', '普拉提', 'yoga', 'pilates'],
    primaryCategory: WorkoutCategory.Cardio,
    muscleWeights: { [WorkoutCategory.Cardio]: 1.0 },
    unit: 'min',
    thresholds: [30, 45, 60, 75, 90],
    strengthFamily: 'none',
    type: 'cardio',
  },
];
