import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
const {chromium}=await import(process.env.PROMO_PLAYWRIGHT || '/Users/kuangqie/.npm/_npx/31e32ef8478fbf80/node_modules/playwright/index.mjs');
const root=resolve(import.meta.dirname,'../..'),out=resolve(root,'docs/media/scenes');mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2});
await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
await page.addInitScript(()=>sessionStorage.setItem('fitgroup_splash_shown','1'));
await page.goto('http://127.0.0.1:4317');
const vector=readFileSync(resolve(import.meta.dirname,'dom-vector.js'),'utf8');
const timeline=[];
async function capture(name,time,title,subtitle){await page.waitForTimeout(650);await page.screenshot({path:resolve(out,name+'.png')});writeFileSync(resolve(out,name+'.svg'),await page.evaluate(`(${vector})()`));timeline.push({name,time,title,subtitle});}
async function click(locator,time){const b=await locator.boundingBox();timeline.at(-1).click={time,x:b.x+b.width/2,y:b.y+b.height/2};await locator.click();await page.waitForTimeout(650);}
await page.getByRole('button',{name:'快速打卡'}).waitFor();
await capture('01-feed',0,'每一次训练，都算数。','FITGROUP / 健友同行');
await click(page.getByRole('button',{name:'快速打卡'}),1.65);
await capture('02-log',2.1,'今天练什么？','01 / 选择动作，开始记录');
await click(page.getByText('常用动作快捷添加'),3.3);
await capture('03-presets',3.7,'常用动作，一点就加。','01 / 选择动作，开始记录');
await click(page.getByRole('button',{name:'哑铃上斜卧推',exact:true}),5.0);
await page.getByText('常用动作快捷添加').click();await page.waitForTimeout(650);
console.log('INPUTS',await page.locator('input').evaluateAll(es=>es.map(e=>({type:e.type,value:e.value,placeholder:e.placeholder}))));
await capture('04-exercise',5.5,'重量、组数、次数。','02 / 把每一组，认真记下来');
const inputs=page.locator('input[type="number"]');await inputs.nth(0).fill('22.5');await inputs.nth(1).fill('4');await inputs.nth(2).fill('10');
await page.getByRole('textbox',{name:'今天状态如何？泵感怎样？记录下来吧...'}).fill('今天的上斜胸，稳稳完成。');
await page.getByRole('button',{name:'发布打卡'}).scrollIntoViewIfNeeded();
await capture('05-ready',7.8,'完成训练，留下记录。','02 / 22.5 KG × 4 组 × 10 次');
await click(page.getByRole('button',{name:'发布打卡'}),9.6);await page.evaluate(()=>window.scrollTo(0,0));
await capture('06-published',10.1,'今日打卡，完成。','03 / 训练记录，出现在动态里');
await click(page.getByRole('button',{name:'统计',exact:true}),12.0);await page.evaluate(()=>window.scrollTo(0,0));
await capture('07-stats',12.5,'看见自己的进步。','04 / 打卡天数 · 训练次数 · 能力分析');
console.log('STATS BUTTONS',await page.getByRole('button').allTextContents());
await page.screenshot({path:resolve(out,'stats-full.png'),fullPage:true});
await page.getByRole('button',{name:'雷达',exact:true}).evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-115));
await capture('08-radar',14.8,'强项与短板，一眼看清。','04 / 能力图谱，了解训练分布');
await click(page.getByRole('button',{name:'条形',exact:true}),16.8);
await capture('09-bars',17.3,'换个角度，读懂训练。','04 / 雷达与条形，自由切换');
await click(page.getByRole('button',{name:'发现',exact:true}),19.2);await page.evaluate(()=>window.scrollTo(0,0));
await capture('10-share-entry',19.7,'把努力，做成战绩。','05 / 一键生成打卡海报');
await click(page.getByRole('button',{name:'生成打卡海报'}).first(),21.0);
await page.evaluate(()=>{for(const el of document.querySelectorAll('main div')){if(getComputedStyle(el).transform!=='none')el.style.transform='none';}});
await capture('11-poster',21.5,'今天的努力，值得留念。','05 / 战绩海报，记录这一练');
await page.screenshot({path:resolve(out,'poster-full.png'),fullPage:true});
writeFileSync(resolve(out,'timeline.json'),JSON.stringify(timeline,null,2));
await browser.close();
